apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels: go
    spec:
      containers:
      - name: go-app
        image: goapp
        ports:
        - containerPort: 9000